### ISSUE TITLE
Tag required for Swift Package

### ISSUE THREAD

**Issue by frogg** [diniska/modal-view#10]
Xcode requires a versioned tag in order to be able to import a package.
I've forked and made the first tage available here:
https://github.com/frogg/modal-view/releases/tag/1.0.0

**Comment by diniska** [comment]
As far as I know, it is not a requirement from Xcode. You can use a branch name to load the code in Xcode. But yeah, I should add a tag. Thanks for working on this!

**Comment by diniska** [comment]
Hello @frogg. The tag has been added to the latest commit https://github.com/diniska/modal-view/releases/tag/1.0.0 after setting up the CI, as now it is supposed to be more stable. Does this resolve the current issue?

**Comment by diniska** [comment]
I'm going to close this issue as the tag `1.0.0` is now added. Please, feel free to create a new one if you have some other concerns.
