### ISSUE TITLE
Dismiss when parent view updates

### ISSUE THREAD

**Issue by p-z-l** [diniska/modal-view#15]
The modal will dismiss after the parent view updates, here's a piece of code that can re-create this bug:
```Swift
import SwiftUI
import ModalView

struct ContentView: View {
    
    @State var demoText = "hello, world"
    
    var body: some View {
        Text(demoText)
        ModalPresenter {
            ModalLink(destination: TextField("", text: $demoText)) {
                Text("Show modal")
            }
        }
    }
    
}
```
Every time the user change the text in the modal sheet, the modal will dismiss unexpectedly. But this no longer happens after removing `Text(demoText)`, so I guess that it dismissed because the parent view was updated.

**Comment by diniska** [comment]
Have you tried moving the ModalPresenter one level upper so that it is not affected by the state change? It is one of the reasons why we separate the `ModalPresenter` and the `ModalLink`.

**Comment by p-z-l** [comment]
It's working for me, thanks!
